# Generated by Django 5.2.17 on 2026-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pen_number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
