# Generated by Django 5.2.17 on 2026-10-05 22:08

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('HARDWARE', 'Hardware Issue (Laptop, Monitor, Mouse)'), ('SOFTWARE', 'Software Access (MS Office, IDEs, OS updates)'), ('NETWORK', 'Network & Wi-Fi Connectivity'), ('ACCOUNT', 'Account Password Reset / Lockout'), ('LOGIN', 'Login issue'), ('OTHER', 'Others (Specify below)')], default='HARDWARE', help_text='Select your request type from the dropdown', max_length=20)),
                ('other_request_text', models.CharField(blank=True, help_text="If you selected 'Others', please specify here", max_length=255, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('attachment', models.FileField(blank=True, help_text='Attach the file', null=True, upload_to=tickets.models.ticket_attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(help_text='The user who created this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='my_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
