# Generated by Django 5.2.17 on 2026-10-07 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='section',
            field=models.CharField(choices=[('ESTABLISHMENT', 'Establishment'), ('PURCHASE', 'Purchase'), ('FINANCE', 'Finance'), ('GRADATION', 'Gradation')], default='ESTABLISHMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_no',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
